# Generated by Django 3.2.5 on 2022-06-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=60)),
                ('apPaterno', models.CharField(max_length=50)),
                ('apMaterno', models.CharField(max_length=50)),
                ('fNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('N', 'Sin especificación'), ('F', 'Femenino'), ('M', 'Masculino')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=20)),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.profesor')),
            ],
        ),
    ]
