# Generated by Django 3.2.5 on 2022-06-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0002_curso_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('registroAula', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tareaAsignatura', models.TextField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('anotacion', models.TextField()),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.profesor')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
