# Generated by Django 3.2.5 on 2022-06-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0005_comunicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(choices=[('-', '-----'), ('N1', 'N°1'), ('N2', 'N°2'), ('N3', 'N°3'), ('N4', 'N°4'), ('N5', 'N°5'), ('N6', 'N°6'), ('N7', 'N°7')], default='-', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.asignatura')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
