# Generated by Django 3.2.5 on 2022-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0008_auto_20220621_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='tipo',
            field=models.CharField(choices=[('-', '-----'), ('N°1', 'N°1'), ('N°2', 'N°2'), ('N°3', 'N°3'), ('N°4', 'N°4'), ('N°5', 'N°5'), ('N°6', 'N°6'), ('N°7', 'N°7')], default='-', max_length=15),
        ),
    ]
