# Generated by Django 3.2.5 on 2022-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0010_alter_comunicacion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
