# Generated by Django 3.2.5 on 2022-06-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0011_auto_20220625_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulacomun',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='controlasignatura',
            name='fecha',
        ),
    ]
