# Generated by Django 3.2.5 on 2022-06-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0012_auto_20220627_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulacomun',
            name='fecha_aula',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='controlasignatura',
            name='fecha_control',
            field=models.DateField(null=True),
        ),
    ]
