# Generated by Django 3.2.5 on 2022-06-29 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0014_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='alumnos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Libro.alumno'),
            preserve_default=False,
        ),
    ]
